[package]
name = "actix-web-validation"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
futures-core = "0.3"
thiserror = "1"
validator = { version = "0.18", optional = true }
garde = { version = "0.19", optional = true }

[features]
default = ["exclusive"]
exclusive = []
validator = ["dep:validator"]
garde = ["dep:garde"]

