[package]
name = "actix-web-validation"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
futures-core = "0.3"
serde = {version = "1", features = ["derive"]}
thiserror = "1.0.61"
validator = { version = "0.18", features = ["derive"] }
