name: Check

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env: 
  CARGO_TERM_COLOR: always

# TODO: Maybe use a matrix and test multiple rust versions
jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@1.79.0
      with: 
        components: clippy, rustfmt

    - uses: Swatinem/rust-cache@v2

    - run: cargo fmt --check
    - run: cargo clippy -- -D warnings


  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@1.79.0
      with: 
        components: llvm-tools-preview

    - uses: Swatinem/rust-cache@v2

    - run: cargo install cargo-llvm-cov

    - name: cargo llvm-cov
      run: cargo llvm-cov --locked --lcov --output-path lcov.info --all-features

    - name: Record Rust version
      run: echo "RUST=$(rustc --version)" >> "$GITHUB_ENV"

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
        env_vars: OS,RUST
